apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: argocd
spec:
  provider:
    vault:
      server: "http://172.16.30.1:8200" # IP Vault
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-role" # Имя роли в Vault UI
          serviceAccountRef:
            name: vault-auth-sa # Аккаунт, который мы создали